### ISSUE TITLE
tpm install - TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by donaldpipowitch** [seanhess/tpm#3]
Step 1: npm install -g typescript-tpm
Step 2: tpm install

Error:

```
/usr/local/lib/node_modules/typescript-tpm/lib/command.js:33
        if (argv.dev.length)
                    ^
TypeError: Cannot read property 'length' of undefined
    at Object.run (/usr/local/lib/node_modules/typescript-tpm/lib/command.js:33:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript-tpm/bin/tpm:6:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

cwd contains package.json and bower.json. Node is v0.10.24.

**Comment by seanhess** [comment]
It doesn't look like this method is what the rest of the community wants, so I'm not really supporting this much. Please refer to https://github.com/DefinitelyTyped/tsd for the tool closest to this that is officially supported.

These days I had DefinitelyTyped as a git submodule and symlink in the definitions I want. 

The `tpm index` command is still useful though. I use it all the time.

**Comment by donaldpipowitch** [comment]
I found tsd some hours ago and use it now. At first glance it was a little bit hard to found out how they differ.

To be honest it is a little confusing for a JS community member to get used to the TS community. E.g. its confusing that "borisyankov/DefinitelyTyped" is more current than "DefinitelyTyped/DefinitelyTyped" if the latter seems to be _more official_. From the view of an outsider it also seems unnecessary that I need tools like tpm or tsd, if simple bower packages would be great to _just get definition files_ (https://github.com/borisyankov/DefinitelyTyped/issues/428).
Anyway, I'm happy to give feedback.

**Comment by seanhess** [comment]
I'm as convinced as you are. The current situation is annoying, but works
ok and there are many parties involved in the decision making.
@Bartvdshttps://github.com/Bartvds is
the man to talk to, I believe.

**Comment by donaldpipowitch** [comment]
Thank you for your feedback!

**Comment by Bartvds** [comment]
Hey @donaldpipowitch

DefinitelyTyped is a bit ad-hoc-organised but still is moving, ever so slowly.
- https://github.com/borisyankov/DefinitelyTyped/issues/556
- https://github.com/borisyankov/DefinitelyTyped/issues/1556
- and filter the issues on [infrastructure](https://github.com/borisyankov/DefinitelyTyped/issues?labels=Infrastructure)
- also there is a new [tsd](https://github.com/DefinitelyTyped/tsd) (0.5) to replace the old one; I'm waiting for the npm credentials to publish it to npm (it has grunt task too). it also needs some of the DT updates to do cool stuff.

Re bower: it is problematic. Long story, comes down to:
- there are over 300 definitions (and growing), would be crazy to maintain/use/watch >300 repos.
- git tagging would be messy: you'd have to continually move tags as current versions receive fixes from users.

This should be fixable in new tsd (needs https://github.com/borisyankov/DefinitelyTyped/issues/1556) but organisation moves a bit slowish. Still both old tsd (0.3.0 on npm) and new (0.5.0 from github) are usable. You can also use NuGet.

**Comment by donaldpipowitch** [comment]
Thank you for the further explanation. I'll watch the TS community closely :)
